name: Tests and Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build project
        run: mvn clean install -DskipTests

      - name: Login Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Build docker image
        run: docker build -t rafaelsantos15/icaro .

      - name: Push image docker
        run: docker push rafaelsantos15/icaro


  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull rafaelsantos15/icaro:latest

      - name: Remove old docker container
        run: docker rm -f icaro

      - name: Run docker container
        run: docker run -d -p 8080:8080 -e APP_DB_USERNAME=${{secrets.APP_DB_USERNAME}} -e APP_DB_PASSWORD='${{secrets.APP_DB_PASSWORD}}' -e APP_DB_URL=${{secrets.APP_DB_URL}} -e SECRET_TOKEN='${{secrets.SECRET_TOKEN}}' -e APP_HOST_EMAIL=${{secrets.APP_HOST_EMAIL}} -e APP_LOGIN_EMAIL='${{secrets.APP_LOGIN_EMAIL}}' -e APP_PORT_EMAIL=${{secrets.APP_PORT_EMAIL}} -e APP_PASSWORD_EMAIL='${{secrets.APP_PASSWORD_EMAIL}}' -e APP_KAFKA_SERVER='${{secrets.APP_KAFKA_SERVER}}'  -e APP_TOPIC_KAFKA_SEND_NEW_EMAIL_SYNC='${{secrets.APP_TOPIC_KAFKA_SEND_NEW_EMAIL_SYNC}}' -e APP_TOPIC_KAFKA_SEND_NEW_EMAIL='${{secrets.APP_TOPIC_KAFKA_SEND_NEW_EMAIL}}' --name icaro rafaelsantos15/icaro
